apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: netwatch
  labels:
    app: api-gateway
    app.kubernetes.io/component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 1000
      containers:
        - name: api-gateway
          image: alexgarzonsoto/netwatch-api-gateway:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: netwatch
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: netwatch-db-secret
                  key: username
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: netwatch-db-secret
                  key: password
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: netwatch-rabbitmq-secret
                  key: username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: netwatch-rabbitmq-secret
                  key: password
            - name: RABBITMQ_VHOST
              value: netwatch
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: netwatch-jwt-secret
                  key: access-secret
            - name: JWT_REFRESH_SECRET
              valueFrom:
                secretKeyRef:
                  name: netwatch-jwt-secret
                  key: refresh-secret
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 30
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
